// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    "Missing required Supabase environment variables: VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY must be set",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Pass-through lock: the default GoTrue lock uses the Navigator Locks API,
// which can deadlock when an auto token refresh holds the lock and a
// .from().select() also tries to acquire it (the data query needs a fresh
// access token, so it queues behind auth). Disabling the lock means token
// refreshes can race, which is fine — the auth server handles concurrent
// refreshes idempotently — and unblocks every data query on first paint.
const passthroughLock = <R>(_n: string, _t: number, fn: () => Promise<R>) =>
  fn();

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      lock: passthroughLock,
    },
  },
);
