// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oejuwrzzzkzodaksaoap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9lanV3cnp6emt6b2Rha3Nhb2FwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNzMwNDMsImV4cCI6MjA2Nzc0OTA0M30.t9A2zYYDuRubB_aRpG9A26JhbXW5ZFI-iX4cjXJcL94";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});